AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'spec/*_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false
