AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'spec/*_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*.rb'
