AllCops:
  TargetRubyVersion: 2.4 
  Exclude:
    - 'db/**/*.rb'
    - 'spec/*_helper.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
