version: '2'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    hostname: app
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    build:
      context: .
      dockerfile: Dockerfile-rails
    command: "bundle exec puma -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - bundle:/bundle
    links:
      - db

volumes:
  db-data:
    driver: local
  bundle:
    driver: local