FROM ruby:2.5.1
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client nodejs
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install
COPY . /frontend
WORKDIR /frontend
