version: '2'
services:
  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql
      - /share

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    volumes_from:
      - db_data
    ports:
      - "5432:5432"

  app:
    hostname: app
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    build:
      context: .
      dockerfile: Dockerfile-rails
    command: "bundle exec puma -p 3000"
    ports:
      - "3000:3000"
    volumes_from:
      - db_data
    links:
      - db
