version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - Shikugawa
      - musaprg
    target_branch: master
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - Shikugawa
      - musaprg
    target_branch: master
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"