version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - Shikugawa
      - musaprg
    target_branch: master
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - Shikugawa
      - musaprg
    target_branch: master